### ISSUE TITLE
Enable firestore environments?

### ISSUE THREAD

**Issue by mrgnhnt96** [SupposedlySam/firefuel#10]

**Comment by mrgnhnt96** [comment]
### "Second" App Instance
We could leave this up to the user to create a "Second App" and pass it in as an instance of Firestore. This doesn't require a lot of work on our end, which could mean that it doesn't really get used.

### Suffix|Prefix Params
We could offer params to create a suffix or prefix depending on the environment. This could be a simple set up that wouldn't require a whole lot of set up on the dev's side
*This could be a plausible solution for `Staging` environments so that the DBs can be reviewed*

### Set up Emulator
I don't have enough experience to have an opinion on this. I just know that it exists. Any thoughts on possibly automating this process for the dev?
*This would really only be used as the dev environment?*

**Comment by SupposedlySam** [comment]
Moved to its own package: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel_env
