### ISSUE TITLE
Create a query method

### ISSUE THREAD

**Issue by mrgnhnt96** [SupposedlySam/firefuel#16]
I wonder if there is a way to simplify the query?

Currently you have to reference the `collectionRef`, add the `where`, `limit`, etc, and then `.get()` to retrieve the docs.

Any of the query methods would be kind of hard to use too, most of them require a `DocumentSnapshot`, which we aren't providing.

**Comment by SupposedlySam** [comment]
Can you provide a code example?

**Comment by SupposedlySam** [comment]
I believe I've come up with a solution in #22. Please provide feedback there.
