### ISSUE TITLE
Platform exception when executing where query

### ISSUE THREAD

**Issue by sam-parks** [SupposedlySam/firefuel#58]
When making a `where` query, this platform exception is sometimes triggered:

<img width="1030" alt="Screen Shot 2021-11-16 at 9 25 28 PM" src="https://user-images.githubusercontent.com/44235716/142159846-b4162509-b528-476f-8206-1d24d417157f.png">

**Comment by SupposedlySam** [comment]
Are you able to provide a stacktrace when this fails? You could try and wrap your code in a try/catch block so next time you're able to report on it.

```dart
try {
  // your code here
} catch(e, stack) {
  // make sure to use the argument above for the stacktrace
}
```

**Comment by SupposedlySam** [comment]
Any update on this @sam-parks ?

**Comment by sam-parks** [comment]
I was never able to reproduce this so we can go ahead and close this!
